languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Nikul Patel's Blog"
logo = "img/knight.png"
description = "My awesome website"

dateFormat = "2 January 2006"

[author]
  name = "Nikul Patel"
  #image = "img/london_bridge.jpg"
  headline = "I hope someone finds this useful."
  bio = "Math major turned programmer"
  links = [
    { email = "mailto:nikulp3141@gmail.com" },
    { github = "https://github.com/nikulpatel462" },
    { linkedin = "https://www.linkedin.com/in/nikul-patel-048a47113/" },
  ]
