baseURL = "/"
theme = "gokarna"

defaultContentLanguage = "en"
languageCode = "en-us"
enableEmoji = true

title = "Nikul Patel's Blog"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources"
    weight = 3
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 2
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "Nikul_Patel_CV.pdf"
    weight = 4
  [[menu.main]]
    identifier = "github"
    name = ""
    url = "https://github.com/nikulpatel462"
    weight = 5
    pre = "<span data-feather='github'></span>"
  [[menu.main]]
    identifier = "linkedin"
    name = ""
    url = "https://www.linkedin.com/in/nikul-patel-048a47113/"
    weight = 6
    pre = "<span data-feather='linkedin'></span>"


[params]
  # URL for the avatar on homepage
  #avatarURL = ""

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = ""

  # Description to display on homepage
  description = ""

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = ""

  # Footer text
  footer = "I always do that, get into something and see how far I can go. ― Richard P. Feynman, Surely You're Joking, Mr. Feynman!"
  copyright = ""

  favicon = "favicon.ico"
